# Generated by Django 5.2.3 on 2025-06-26 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.currency')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='card_logos/')),
                ('active', models.BooleanField(default=True)),
                ('countries', models.ManyToManyField(blank=True, to='cards.country')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('card_type', models.CharField(choices=[('physical', 'Physical Card'), ('ecode', 'E-code')], default='physical', max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cards.giftcard')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.country')),
            ],
            options={
                'ordering': ['min_value'],
                'unique_together': {('card', 'country', 'min_value', 'max_value', 'card_type')},
            },
        ),
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('physical', 'Physical Card'), ('ecode', 'E-code')], max_length=10)),
                ('card_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=100)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Pending Payment'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.transaction')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.country')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.currency')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.giftcard')),
                ('card_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.giftcardrate')),
            ],
        ),
    ]
